---

taps:
  - caskroom/cask
  - caskroom/versions
  - homebrew/dupes
  - homebrew/versions
  - homebrew/boneyard
  - homebrew/binary

packages:
  - { name: ansible, state: present }
  - { name: awscli, state: present }
  - { name: git, state: present }
